name = "My Modpack"
author = "your-team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3dae138f8d97ed6c34af889f064e4e6d812d6d96aff2841c55091ffac5fa8e02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.95"
