name = "My Modpack"
author = "your-team"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ab421bc9d6e3117e274eb75670181165d72c2e78625a50e37b1b0d741f37407c"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.95"
