name = "Sky Ratlandia"
author = "Baxjax, Danjo"
version = "0.1.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0c76de6a227b98ec4e4948268721237d93e8954e65030b195b7d990acf9d9333"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
